artifacts:
  dia_object_lc_10plus:
    format: hats-collection
    hash: sha256:9bf5b115999211243d05db8dfd7017cbcea33b24284bce1a53fda0eb0dcfb942
    inputs: []
    notes: '4 diaObject partitions (order 7), nDiaSources > 10: 2 low/high galactic
      latitude x 2 low/high cadence (max nDiaSources), see nb_01 section 3.'
    path: dia_object_lc_10plus/collection.properties
    root: dp2_subset
    tags:
    - diaobject
    - dp2
    - nb01
    type: dp2_subset
    updated_at: '2026-08-27T16:10:23+00:00'
    updated_by: shrra-ung
registry_version: 1
